* Ethical guidelines of a superintelligence

  http://www.cs.nyu.edu/faculty/davise/papers/Bostrom.pdf

  file:articles/Ethical_guidelines.pdf

  A review of bostrom's "SuperIntelligence: Paths, Dangers, Stategies".

  Critical of bostrom, bostrom is exaggerating.

  Probably not useful to our essay, perhaps if we also study above
  mentioned book.

  #+BEGIN_QUOTE
  developing an understanding of ethics as contemporary humans
  understand it is actually one of the easier problems facing AI
  #+END_QUOTE

  Stupid to give anyone carte blanche to do something, wether and AI
  or human.

* Roboethics: Social and Ethical Implications of Robotics

  file:articles/Roboethics.pdf

  Predicts humanoid robots in the next decades.

  Roboethics: human ethic of robot designers etc. Not ethics of robot AIs.

  P. 1505: Moral theories, good reference?

  Korean Roboethics Charter being developed.

  #+BEGIN_QUOTE
  Humanoids are the expression of one of the demands of oru European
  culture, that is, that humankind be the creator of some mechanical
  being in the shape of a human. In Japanese culture, it is the demand
  to carefully replicate nature in all its forms.
  #+END_QUOTE

  Some useful definitions of many concepts in robotics/AI that can be useful.

* Artificial intelligence as a positive and negative factor in global risk

  file:articles/AIPosNegFactor.pdf

  "A superintelligence could make a super giant cheesecake".

*
